apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring 
  namespace: dev 
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: spring 
  template: 
    metadata:
      name: spring
      labels: 
        app: spring 
    spec: 
      containers: 
      - name: spring 
        image: acadalearning/cohort14:1.1.0 
        ports: 
        - containerPort: 8080

---
apiVersion: v1 
kind:  Service 
metadata:
  name: spring 
  namespace: dev 
spec: 
  type: LoadBalancer
  selector: 
    app: spring 
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 31500
