apiVersion: v1
kind: Pod 
metadata:
  name: rbclogging
  namespace: dev
spec: 
  containers: 
  - name: password
    image: acadalearning/cohort14:1.1.0
    ports: 
    - containerPort: 8080
  - name: fingerprint
    image: nginx:stable-perl
    ports: 
    - containerPort: 80

