apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: mongo 
  namespace: dev 
  annotations: 
    imageversion: "2.5.3"
    imageregistry: "https://hub.docker.com/repository/docker/ladebz/devops/general"
    author: "LaDebz"
spec: 
  selector: 
    matchLabels:
      app: mongo 
  template: 
    metadata:
      name: mongo 
      labels: 
        app: mongo
    spec: 
      volumes: 
      - name: nfsvol
        nfs: 
          server: 172.31.26.171
          path: /mnt/share
      - name: nfs-pv
        persistentVolumeClaim: 
          claimName: nfs-pvc
      containers: 
      - name: mongo 
        image: mongo
        ports: 
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
        volumeMounts: 
        - name: nfsvol
          mountPath: /data/db

---

apiVersion: v1 
kind: Service 
metadata:
  name: mongo 
  namespace: dev 
spec: 
  selector: 
    app: mongo 
  type: ClusterIP
  ports:
  - port: 27017 
    targetPort: 27017 
