apiVersion: v1
kind: ReplicationController
metadata:
  name: controller-rc
  namespace: dev 
spec:
  selector:
    app: spring
  template: 
    metadata:
      name: controller-pod
      labels:
        app: spring
    spec: 
      containers: 
      - name: controller-con
        image: acadalearning/cohort14:1.1.0
        ports: 
        - containerPort: 8080
