apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deplacc
  namespace: dev 
spec: 
  replicas: 10
  selector: 
    matchLabels:
      app: accountcreation
  strategy: 
    type: Recreate 
  template: 
    metadata:
      name: acccreatepod
      labels: 
        app: accountcreation
    spec: 
      containers: 
      - name: createcon
        image: acadalearning/cohort14:1.1.0
        ports: 
        - containerPort: 8080 

--- 
apiVersion: v1
kind: Service 
metadata:
  name: createsvc
  namespace: dev 
spec: 
  type: LoadBalancer 
  selector: 
    app: accountcreation
  ports: 
  - targetPort: 8080
    port: 80 
    protocol: TCP
