apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deplacc
  namespace: testing
spec: 
  replicas: 0
  selector: 
    matchLabels:
      app: accountcreation
  strategy: 
    type: Recreate 
  template: 
    metadata:
      name: acccreatepod
      labels: 
        app: accountcreation
    spec: 
      containers: 
      - name: createcon
        image: ladebz/devops:devconsult-1.1
        ports: 
        - containerPort: 8081 

--- 
apiVersion: v1
kind: Service 
metadata:
  name: createsvc
  namespace: testing 
spec: 
  type: LoadBalancer 
  selector: 
    app: accountcreation
  ports: 
  - targetPort: 8080
    port: 80 
    protocol: TCP
