apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring  # Make sure this matches the label in the selector
    spec:
      containers:
      - name: cohort15-con
        image: acadalearning/cohort14:1.1.0
        ports:
        - containerPort: 8080

