apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: nginx
spec: 
  selector:
    matchLabels:
      app: nginx 
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:alpine3.18-perl
