apiVersion: apps/v1 # The version of the Kubernetes API
kind: ReplicaSet # The kind of resource, which is a ReplicaSet in this case
metadata:
  name: mongo # The name of the ReplicaSet
  namespace: dev # The namespace in which the ReplicaSet will be created
  annotations: 
    imageversion: "2.5.3" # Annotation to specify the image version
    imageregistry: "https://hub.docker.com/repository/docker/acadalearning/spring-boot-mongo/general" # Annotation to specify the image registry
    author: "LaDebz" # Annotation to specify the author
spec: 
  selector: 
    matchLabels:
      app: mongo # The label selector to identify pods managed by this ReplicaSet
  template: 
    metadata:
      name: mongo # The name of the pod template
      labels: 
        app: mongo # The labels assigned to the pods created from this template
    spec: 
      volumes: 
      - name: hostpathvol # The name of the volume
        hostPath: 
          path: /tmp/mongodb # The host path directory to mount into the pod
      containers: 
      - name: mongo # The name of the container
        image: mongo # The Docker image to use for the container
        ports: 
        - containerPort: 27017 # The port exposed by the container
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME # Environment variable for MongoDB username
          value: devdb # The value for the MongoDB username
        - name: MONGO_INITDB_ROOT_PASSWORD # Environment variable for MongoDB password
          value: devdb@123 # The value for the MongoDB password
        volumeMounts: 
        - name: hostpathvol # The name of the volume to mount
          mountPath: /data/db # The path in the container where the volume will be mounted

# /tmp/mongodb:/data/db

---

apiVersion: v1 # The version of the Kubernetes API
kind: Service # The kind of resource, which is a Service in this case
metadata:
  name: mongo # The name of the Service
  namespace: dev # The namespace in which the Service will be created
spec: 
  selector: 
    app: mongo # The label selector to identify pods targeted by this Service
  type: ClusterIP # The type of Service, which is ClusterIP in this case
  ports:
  - port: 27017 # The port that the Service will expose
    targetPort: 27017 # The port on the pod to which traffic will be directed
