apiVersion: apps/v1
kind: Deployment 
metadata:
  name: spring
  namespace: dev 
  annotations: 
    imageversion: "2.5.3"
    imageregistry: "https://hub.docker.com/repository/docker/ladebz/devops/general"
    authur: "LaDebz"
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: spring 
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template: 
    metadata:
      name: spring
      labels: 
        app: spring
    spec: 
      containers: 
      - name: spring 
        image: acadalearning/spring-boot-mongo
        ports: 
        - containerPort: 8080 
        env:
        - name: MONGO_DB_USERNAME
          valueFrom: 
            configMapKeyRef: 
              name: spring-cm
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: spring-sc
              key: mongo-pw
        - name: MONGO_DB_HOSTNAME
          valueFrom: 
            configMapKeyRef: 
              name: spring-cm
              key: hostname

--- 
apiVersion: v1 
kind: Service 
metadata:
  name: spring 
  namespace: dev 
spec: 
  type: NodePort 
  selector:
    app: spring
  ports: 
  - targetPort: 8080
    port: 80
    protocol: TCP 
    nodePort: 32000
